### PR TITLE
Space added: Maschinenraum

### PR DESCRIPTION
**Pull request by eins78**
http://api.maschinenraum.tk/status.json

### CODE REVIEW

**Comment by slopjong** [comment]
I took my pocket-sized home server with me when I went home for christmas and forgot to put it online. I'll merge and check it later this day.

**Comment by eins78** [comment]
Thanks. Mind that I also added it via the OpenDirectory web interface (with a slightly different URL), so just ignore it.

**Comment by slopjong** [comment]
Which one has to be ignored?

As soon as I put my home server online the push script will merge the version from the OpenDirectory web interface with the github's version and not vice versa. The push script doesn't pull from the git repository as it expects (forces) that new spaces are added through the web interface to ensure that the json is a valid space api implementation.

**Comment by eins78** [comment]
URL used while testing, _to be ignored_: http://api.maschinenraum.tk/spaceapi.json
Final URL using the recommended slug: http://api.maschinenraum.tk/status.json

Or did i miss an 'edit' button in the OpenDirectory? (I don't think so since there is no auth).

**Comment by slopjong** [comment]
Done.

**Pull request closed without merging**
