### PR TITLE
Update nbsp

### PR DESCRIPTION
**Pull request by makomi**

### CODE REVIEW

**Comment by slopjong** [comment]
Done.

**Comment by makomi** [comment]
It looks like you did not accept my pull request. The Nbsp's SpaceAPI URL in this repo remains incorrect.

However, [spaceapi.net/directory.json](http://spaceapi.net/directory.json) lists the correct URL. How are these two lists synced? Which of both is the primary list?

**Comment by slopjong** [comment]
> It looks like you did not accept my pull request.

Yes, that's true.

OpenSpaceDirectory was part of the very first version of the SpaceAPI. At that time the website looked like on the screenshot. Many features have been developed since then while one of them was a caching system which allows a hackerspace to protect their endpoint from being flooded. That's the .../cache/... URLs you see in the directory that hide the actual endpoint URLs. That's the reason why the directory is no longer pushed to this repo.

The directory is dynamically regenerated after the daily revalidation of all the endpoints. Broken endpoints are replaced by the Cache URLs to not break SpaceAPI consumers.

I hope how the SpaceAPI works has become more clear.

**Comment by makomi** [comment]
Ah, too bad I can't directly edit the directory. Thanks for pointing this out and excuse me for not reading the README properly.

**Comment by slopjong** [comment]
How would you do it? The cache wouldn't make sense if all the endpoints were public. Some spaces _want_ their URL hidden to avoid mass requests. SpaceAPI consumers would use Github as a CDN and bypass the cache.

**Comment by makomi** [comment]
What I meant was, that I was looking forward to contributing directly instead of indirectly, i.e. instead of just opening a ticket. That comment did not judge your implementation but was an expression of personal preference–it was the first pull request I sent on Github :-)

I agree, that if you want people to use the cached version, you can't at the same time make the hidden endpoint URLs public. However, currently the URLs of some endpoints are public via [OpenSpaceDirectory/directory.json](https://github.com/slopjong/OpenSpaceDirectory/blob/master/directory.json), although their URLs are hidden in [spaceapi.net/directory.json](http://spaceapi.net/directory.json). Is this intentional/ an issue?

I think it would it be feasible to maintain a directory.json on Github, that looks just like [spaceapi.net/directory.json](http://spaceapi.net/directory.json) while keeping [spaceapi.net/directory.json](http://spaceapi.net/directory.json) the primary directory. Whenever the external server behind spaceapi.net is scheduled to validate all endpoints' URLs, it (1) pulls the repository from Github, (2) performs its endpoint validation, (3) if necessary replaces broken endpoint URLs with cache URLs, and (4) commits + pushes. In order for changes to the Github repo to become effective in a timely manner, the server could pull the Github repository every 15 minutes or so. Prior to every server side change of directory.json (change of an endpoint's URL or addition of a new endpoint) the server would of course have to pull the repository from Github.

The advantage of this would be, that [OpenSpaceDirectory/directory.json](https://github.com/slopjong/OpenSpaceDirectory/blob/master/directory.json) would stay in sync with [spaceapi.net/directory.json](http://spaceapi.net/directory.json) and that people can interact with this repository like they are used to from other Github repos.

**Comment by makomi** [comment]
What are your thoughts on this?

**Comment by slopjong** [comment]
The last modification of the directory repo was two years ago at a time where the newly developed cache hasn't been in production yet. Happy birthday "Cache" :-)

What about
- SpaceAPI generates a token
- Hackerspace that wants to change the URL need to create a file with that content in the old endpoint location.
- SpaceAPI validates the existence of this file and accepts/refuses the change.
- Hackerspace doesn't do anything ➜ token invalidates after 10 minutes, automatically.

By doing so you'd be able to change it immediately without making the directory fully public.

**Comment by makomi** [comment]
I like your approach much better than mine. Having a cache easily makes the setup more complex.

Thank you for taking the time to talk about this :-)

**Pull request closed without merging**
